---
- name: Spin up some EC2 instances
  hosts: ubuntu@ec2-54-68-175-48.us-west-2.compute.amazonaws.com 
  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        name: ansible-test 
        description: Access ansible-test 
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Launch instances
      local_action:
        module: ec2
        region: us-west-2
        image: ami-11551e21
        keypair: ansible-test 
        group: ansible-test 
        instance_type: t2.micro
        count: 2 
        wait: yes
    - name: Add instances to host group
      local_action: add_host hostname= groupname=ansible-test
      with_items: ec2.instances
