---
- name: Spin up some EC2 instances
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        name: my-security-group
        description: Access my-security-group
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Launch instances
      local_action:
        module: ec2
        region: us-west-2
        image: ami-f9165ec9
        keypair: ansible-test 
        group: my-security-group
        instance_type: t2.micro
        count: 2 
        wait: yes
       #register: ec2_info
